=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngineApi::CarriersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CarriersApi' do
  before do
    # run before each test
    @instance = ShipEngineApi::CarriersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CarriersApi' do
    it 'should create an instance of CarriersApi' do
      expect(@instance).to be_instance_of(ShipEngineApi::CarriersApi)
    end
  end

  # unit tests for carriers_add_funds
  # 
  # 
  # @param carrier_id 
  # @param amount_to_add 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [BalanceResponse]
  describe 'carriers_add_funds test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for carriers_get
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Carrier]
  describe 'carriers_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for carriers_get_options
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [CarrierListOptionsResponse]
  describe 'carriers_get_options test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for carriers_list
  # 
  # 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [CarrierListResponse]
  describe 'carriers_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for carriers_list_packages
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [CarrierListPackagesResponse]
  describe 'carriers_list_packages test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for carriers_list_services
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [CarrierListServicesResponse]
  describe 'carriers_list_services test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
