=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngineApi::CarrierAccountsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CarrierAccountsApi' do
  before do
    # run before each test
    @instance = ShipEngineApi::CarrierAccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CarrierAccountsApi' do
    it 'should create an instance of CarrierAccountsApi' do
      expect(@instance).to be_instance_of(ShipEngineApi::CarrierAccountsApi)
    end
  end

  # unit tests for access_worldwide_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'access_worldwide_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for access_worldwide_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'access_worldwide_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apc_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'apc_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apc_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'apc_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for asendia_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'asendia_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for asendia_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'asendia_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for d_hl_express_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'd_hl_express_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for d_hl_express_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'd_hl_express_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for d_hl_express_account_carrier_update_settings
  # 
  # 
  # @param carrier_id 
  # @param settings 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'd_hl_express_account_carrier_update_settings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for endicia_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'endicia_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for endicia_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'endicia_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fed_ex_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'fed_ex_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fed_ex_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'fed_ex_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fed_ex_account_carrier_update_settings
  # 
  # 
  # @param carrier_id 
  # @param settings 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'fed_ex_account_carrier_update_settings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for first_mile_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'first_mile_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for first_mile_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'first_mile_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for globegistics_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'globegistics_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for globegistics_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'globegistics_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for imex_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'imex_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for imex_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'imex_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for newgistics_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'newgistics_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for newgistics_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'newgistics_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for newgistics_account_carrier_update_settings
  # 
  # 
  # @param carrier_id 
  # @param settings 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'newgistics_account_carrier_update_settings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for on_trac_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'on_trac_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for on_trac_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'on_trac_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for rr_donnelley_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'rr_donnelley_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for rr_donnelley_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'rr_donnelley_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for stamps_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'stamps_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for stamps_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'stamps_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for u_ps_account_carrier_connect_account
  # 
  # 
  # @param model 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'u_ps_account_carrier_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for u_ps_account_carrier_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'u_ps_account_carrier_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for u_ps_account_carrier_update_settings
  # 
  # 
  # @param carrier_id 
  # @param settings 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'u_ps_account_carrier_update_settings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
