=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngine::CarrierAccountsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CarrierAccountsApi' do
  before do
    # run before each test
    @instance = ShipEngine::CarrierAccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CarrierAccountsApi' do
    it 'should create an instance of CarrierAccountsApi' do
      expect(@instance).to be_instance_of(ShipEngine::CarrierAccountsApi)
    end
  end

  # unit tests for access_worldwide_connect_account
  # 
  # 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'access_worldwide_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for access_worldwide_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'access_worldwide_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apc_connect_account
  # 
  # 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'apc_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apc_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'apc_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for asendia_connect_account
  # 
  # 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'asendia_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for asendia_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'asendia_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for dhl_express_connect_account
  # 
  # 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'dhl_express_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for dhl_express_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'dhl_express_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for dhl_express_update_settings
  # 
  # 
  # @param carrier_id 
  # @param settings 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'dhl_express_update_settings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for endicia_connect_account
  # 
  # 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'endicia_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for endicia_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'endicia_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fedex_connect_account
  # 
  # 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'fedex_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fedex_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'fedex_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fedex_update_settings
  # 
  # 
  # @param carrier_id 
  # @param settings 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'fedex_update_settings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for first_mile_connect_account
  # 
  # 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'first_mile_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for first_mile_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'first_mile_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for globegistics_connect_account
  # 
  # 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'globegistics_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for globegistics_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'globegistics_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for imex_connect_account
  # 
  # 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'imex_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for imex_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'imex_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for on_trac_connect_account
  # 
  # 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'on_trac_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for on_trac_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'on_trac_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for rr_donnelley_connect_account
  # 
  # 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'rr_donnelley_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for rr_donnelley_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'rr_donnelley_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for stamps_connect_account
  # 
  # 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'stamps_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for stamps_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'stamps_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ups_connect_account
  # 
  # 
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseDTO]
  describe 'ups_connect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ups_disconnect_account
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'ups_disconnect_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ups_update_settings
  # 
  # 
  # @param carrier_id 
  # @param settings 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'ups_update_settings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
