=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngine::CarriersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CarriersApi' do
  before do
    # run before each test
    @instance = ShipEngine::CarriersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CarriersApi' do
    it 'should create an instance of CarriersApi' do
      expect(@instance).to be_instance_of(ShipEngine::CarriersApi)
    end
  end

  # unit tests for get
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [Carrier]
  describe 'get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_options
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [CarrierListOptionsResponse]
  describe 'get_options test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @return [CarrierListResponse]
  describe 'list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_packages
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [CarrierListPackagesResponse]
  describe 'list_packages test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_services
  # 
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [CarrierListServicesResponse]
  describe 'list_services test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
