=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngineApi::EnvironmentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EnvironmentApi' do
  before do
    # run before each test
    @instance = ShipEngineApi::EnvironmentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EnvironmentApi' do
    it 'should create an instance of EnvironmentApi' do
      expect(@instance).to be_instance_of(ShipEngineApi::EnvironmentApi)
    end
  end

  # unit tests for environment_create_webhook
  # 
  # 
  # @param create_webhook_dto 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [WebhookDTO]
  describe 'environment_create_webhook test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for environment_delete_webhook
  # 
  # 
  # @param webhook_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'environment_delete_webhook test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for environment_get_webhook_by_id
  # 
  # 
  # @param webhook_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [WebhookDTO]
  describe 'environment_get_webhook_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for environment_update_webhook
  # 
  # 
  # @param webhook_id 
  # @param update_webhook_dto 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'environment_update_webhook test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for environment_webhooks
  # 
  # 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Array<WebhookDTO>]
  describe 'environment_webhooks test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for environment_whoami
  # 
  # 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'environment_whoami test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
