=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngineApi::InsuranceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InsuranceApi' do
  before do
    # run before each test
    @instance = ShipEngineApi::InsuranceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InsuranceApi' do
    it 'should create an instance of InsuranceApi' do
      expect(@instance).to be_instance_of(ShipEngineApi::InsuranceApi)
    end
  end

  # unit tests for insurance_add_funds
  # 
  # 
  # @param cost 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [MoneyDTO]
  describe 'insurance_add_funds test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for insurance_get_balance
  # 
  # 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [MoneyDTO]
  describe 'insurance_get_balance test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
