=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngineApi::LabelsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LabelsApi' do
  before do
    # run before each test
    @instance = ShipEngineApi::LabelsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LabelsApi' do
    it 'should create an instance of LabelsApi' do
      expect(@instance).to be_instance_of(ShipEngineApi::LabelsApi)
    end
  end

  # unit tests for labels_get
  # 
  # 
  # @param label_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Label]
  describe 'labels_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for labels_list
  # 
  # 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :batch_id 
  # @option opts [String] :label_status 
  # @option opts [String] :carrier_id 
  # @option opts [String] :service_code 
  # @option opts [String] :tracking_number 
  # @option opts [String] :warehouse_id 
  # @option opts [DateTime] :created_at_start 
  # @option opts [DateTime] :created_at_end 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @option opts [String] :sort_dir 
  # @option opts [String] :sort_by 
  # @return [ListLabelResponse]
  describe 'labels_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for labels_purchase_label
  # 
  # 
  # @param request 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Label]
  describe 'labels_purchase_label test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for labels_purchase_label_with_rate
  # 
  # 
  # @param rate_id 
  # @param request 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Label]
  describe 'labels_purchase_label_with_rate test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for labels_purchase_label_with_shipment
  # 
  # 
  # @param shipment_id 
  # @param request 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Label]
  describe 'labels_purchase_label_with_shipment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for labels_track
  # 
  # 
  # @param label_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [TrackingInformation]
  describe 'labels_track test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for labels_void_label
  # 
  # 
  # @param label_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [VoidLabelResponse]
  describe 'labels_void_label test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
