=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngine::ManifestsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ManifestsApi' do
  before do
    # run before each test
    @instance = ShipEngine::ManifestsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ManifestsApi' do
    it 'should create an instance of ManifestsApi' do
      expect(@instance).to be_instance_of(ShipEngine::ManifestsApi)
    end
  end

  # unit tests for create
  # 
  # 
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [Manifest]
  describe 'create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # 
  # 
  # @param manifest_id 
  # @param [Hash] opts the optional parameters
  # @return [Manifest]
  describe 'get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :warehouse_id 
  # @option opts [DateTime] :ship_date_start 
  # @option opts [DateTime] :ship_date_end 
  # @option opts [DateTime] :created_at_start 
  # @option opts [DateTime] :created_at_end 
  # @option opts [String] :carrier_id 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @return [ManifestsListResponse]
  describe 'list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
