=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngineApi::PackagesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PackagesApi' do
  before do
    # run before each test
    @instance = ShipEngineApi::PackagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PackagesApi' do
    it 'should create an instance of PackagesApi' do
      expect(@instance).to be_instance_of(ShipEngineApi::PackagesApi)
    end
  end

  # unit tests for packages_create
  # 
  # 
  # @param package 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Package]
  describe 'packages_create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for packages_delete
  # 
  # 
  # @param package_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'packages_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for packages_get
  # 
  # 
  # @param package_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Package]
  describe 'packages_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for packages_list
  # 
  # 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [PackagesListResponse]
  describe 'packages_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for packages_update
  # 
  # 
  # @param package_id 
  # @param package 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'packages_update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
