=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngineApi::RatesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RatesApi' do
  before do
    # run before each test
    @instance = ShipEngineApi::RatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RatesApi' do
    it 'should create an instance of RatesApi' do
      expect(@instance).to be_instance_of(ShipEngineApi::RatesApi)
    end
  end

  # unit tests for rates_estimate
  # 
  # 
  # @param estimate_request 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Array<Rate>]
  describe 'rates_estimate test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for rates_get
  # 
  # 
  # @param rate_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Rate]
  describe 'rates_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for rates_rate_shipment
  # 
  # 
  # @param request 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [RateShipmentResponse]
  describe 'rates_rate_shipment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for rates_rate_shipments_async
  # 
  # 
  # @param request 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Array<RateResponseAsync>]
  describe 'rates_rate_shipments_async test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
