=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngineApi::ShipmentsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ShipmentsApi' do
  before do
    # run before each test
    @instance = ShipEngineApi::ShipmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ShipmentsApi' do
    it 'should create an instance of ShipmentsApi' do
      expect(@instance).to be_instance_of(ShipEngineApi::ShipmentsApi)
    end
  end

  # unit tests for shipments_add_tag
  # 
  # 
  # @param shipment_id 
  # @param tag 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [ShipmentAddTagResponse]
  describe 'shipments_add_tag test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for shipments_cancel
  # 
  # 
  # @param shipment_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'shipments_cancel test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for shipments_create_shipments
  # 
  # 
  # @param shipments_request 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [CreateShipmentsResponse]
  describe 'shipments_create_shipments test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for shipments_get
  # 
  # 
  # @param shipment_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Shipment]
  describe 'shipments_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for shipments_get_by_external_id
  # 
  # 
  # @param external_shipment_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [Shipment]
  describe 'shipments_get_by_external_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for shipments_get_rates_for_shipment
  # 
  # 
  # @param shipment_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @option opts [DateTime] :created_at_start 
  # @return [RateResponse]
  describe 'shipments_get_rates_for_shipment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for shipments_list
  # 
  # 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :batch_id 
  # @option opts [String] :tag 
  # @option opts [String] :shipment_status 
  # @option opts [DateTime] :modified_at_start 
  # @option opts [DateTime] :modified_at_end 
  # @option opts [DateTime] :created_at_start 
  # @option opts [DateTime] :created_at_end 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @option opts [String] :sort_dir 
  # @option opts [String] :sort_by 
  # @return [ListShipmentResponse]
  describe 'shipments_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for shipments_list_errors
  # 
  # 
  # @param shipment_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :pagesize 
  # @return [ShipmentResponseErrors]
  describe 'shipments_list_errors test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for shipments_remove_tag
  # 
  # 
  # @param shipment_id 
  # @param tag 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'shipments_remove_tag test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for shipments_update_shipment
  # 
  # 
  # @param shipment_id 
  # @param shipment 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [CreateShipmentResponse]
  describe 'shipments_update_shipment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
