=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngine::ShipmentsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ShipmentsApi' do
  before do
    # run before each test
    @instance = ShipEngine::ShipmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ShipmentsApi' do
    it 'should create an instance of ShipmentsApi' do
      expect(@instance).to be_instance_of(ShipEngine::ShipmentsApi)
    end
  end

  # unit tests for add_tag
  # 
  # 
  # @param shipment_id 
  # @param tag 
  # @param [Hash] opts the optional parameters
  # @return [ShipmentAddTagResponse]
  describe 'add_tag test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cancel
  # 
  # 
  # @param shipment_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cancel test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create
  # 
  # 
  # @param shipments_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateShipmentsResponse]
  describe 'create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # 
  # 
  # @param shipment_id 
  # @param [Hash] opts the optional parameters
  # @return [Shipment]
  describe 'get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_by_external_id
  # 
  # 
  # @param external_shipment_id 
  # @param [Hash] opts the optional parameters
  # @return [Shipment]
  describe 'get_by_external_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_rates_for_shipment
  # 
  # 
  # @param shipment_id 
  # @param [Hash] opts the optional parameters
  # @option opts [DateTime] :created_at_start 
  # @return [RateResponse]
  describe 'get_rates_for_shipment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :batch_id 
  # @option opts [String] :tag 
  # @option opts [String] :shipment_status 
  # @option opts [DateTime] :modified_at_start 
  # @option opts [DateTime] :modified_at_end 
  # @option opts [DateTime] :created_at_start 
  # @option opts [DateTime] :created_at_end 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @option opts [String] :sort_dir 
  # @option opts [String] :sort_by 
  # @return [ListShipmentResponse]
  describe 'list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_errors
  # 
  # 
  # @param shipment_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :pagesize 
  # @return [ShipmentResponseErrors]
  describe 'list_errors test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_tag
  # 
  # 
  # @param shipment_id 
  # @param tag 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'remove_tag test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update
  # 
  # 
  # @param shipment_id 
  # @param shipment 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
