=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngineApi::WarehousesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WarehousesApi' do
  before do
    # run before each test
    @instance = ShipEngineApi::WarehousesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WarehousesApi' do
    it 'should create an instance of WarehousesApi' do
      expect(@instance).to be_instance_of(ShipEngineApi::WarehousesApi)
    end
  end

  # unit tests for warehouses_create
  # 
  # 
  # @param request 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [WarehouseDTO]
  describe 'warehouses_create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for warehouses_delete
  # 
  # 
  # @param warehouse_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'warehouses_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for warehouses_get
  # 
  # 
  # @param warehouse_id 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [WarehouseDTO]
  describe 'warehouses_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for warehouses_list
  # 
  # 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [WarehouseListDTO]
  describe 'warehouses_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for warehouses_update
  # 
  # 
  # @param warehouse_id 
  # @param request 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'warehouses_update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
