=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ShipEngine::FedExAccountSettingsDTO
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FedExAccountSettingsDTO' do
  before do
    # run before each test
    @instance = ShipEngine::FedExAccountSettingsDTO.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FedExAccountSettingsDTO' do
    it 'should create an instance of FedExAccountSettingsDTO' do
      expect(@instance).to be_instance_of(ShipEngine::FedExAccountSettingsDTO)
    end
  end
  describe 'test attribute "nickname"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "pickup_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["none", "regular_pickup", "request_courier", "drop_box", "business_service_center", "station"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.pickup_type = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "smart_post_hub"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["none", "allentown_pa", "atlanta_ga", "charlotte_nc", "chino_ca", "dallas_tx", "denver_co", "detroit_mi", "edison_nj", "grove_city_oh", "groveport_oh", "houston_tx", "indianapolis_in", "kansas_city_ks", "los_angeles_ca", "martinsburg_wv", "memphis_tn", "minneapolis_mn", "new_berlin_wi", "northborough_ma", "orlando_fl", "phoneix_az", "pittsburgh_pa", "reno_nv", "sacramento_ca", "salt_lake_city_ut", "seattle_wa", "st_louis_mo"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.smart_post_hub = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "smart_post_endorsement"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["none", "return_service_requested", "forwarding_service_requested", "address_service_requested", "change_service_requested", "leave_if_no_response"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.smart_post_endorsement = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "is_primary_account"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

