=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ShipEngineApi::ModifyBatchRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ModifyBatchRequest' do
  before do
    # run before each test
    @instance = ShipEngineApi::ModifyBatchRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ModifyBatchRequest' do
    it 'should create an instance of ModifyBatchRequest' do
      expect(@instance).to be_instance_of(ShipEngineApi::ModifyBatchRequest)
    end
  end
  describe 'test attribute "shipment_ids"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "rate_ids"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

