=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ShipEngineApi::MoneyDTO
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MoneyDTO' do
  before do
    # run before each test
    @instance = ShipEngineApi::MoneyDTO.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MoneyDTO' do
    it 'should create an instance of MoneyDTO' do
      expect(@instance).to be_instance_of(ShipEngineApi::MoneyDTO)
    end
  end
  describe 'test attribute "currency"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["uSD", "cAD", "aUD", "gBP", "eUR"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.currency = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "amount"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

