=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ShipEngine::ProcessBatchRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProcessBatchRequest' do
  before do
    # run before each test
    @instance = ShipEngine::ProcessBatchRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProcessBatchRequest' do
    it 'should create an instance of ProcessBatchRequest' do
      expect(@instance).to be_instance_of(ShipEngine::ProcessBatchRequest)
    end
  end
  describe 'test attribute "ship_date"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

