=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ShipEngineApi::ProcessBatchRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProcessBatchRequest' do
  before do
    # run before each test
    @instance = ShipEngineApi::ProcessBatchRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProcessBatchRequest' do
    it 'should create an instance of ProcessBatchRequest' do
      expect(@instance).to be_instance_of(ShipEngineApi::ProcessBatchRequest)
    end
  end
  describe 'test attribute "ship_date"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "label_layout"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "label_format"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["pdf", "zpl", "png"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.label_format = value }.not_to raise_error
       #end
    end
  end

end

