=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require "uri"

module ShipEngine
  class TrackingApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :carrier_code 
    # @option opts [String] :tracking_number 
    # @return [nil]
    def start_tracking(opts = {})
      start_tracking_with_http_info(opts)
      return nil
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :carrier_code 
    # @option opts [String] :tracking_number 
    # @return [nil]
    def stop_tracking(opts = {})
      stop_tracking_with_http_info(opts)
      return nil
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :carrier_code 
    # @option opts [String] :tracking_number 
    # @return [TrackingInformation]
    def track(opts = {})
      data, _status_code, _headers = track_with_http_info(opts)
      return data
    end

    private

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :carrier_code 
    # @option opts [String] :tracking_number 
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def start_tracking_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: TrackingApi.start_tracking ..."
      end
      # resource path
      local_var_path = "/v1/tracking/start"

      # query parameters
      query_params = {}
      query_params[:'carrier_code'] = opts[:'carrier_code'] if !opts[:'carrier_code'].nil?
      query_params[:'tracking_number'] = opts[:'tracking_number'] if !opts[:'tracking_number'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['api-key']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrackingApi#start_tracking\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :carrier_code 
    # @option opts [String] :tracking_number 
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def stop_tracking_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: TrackingApi.stop_tracking ..."
      end
      # resource path
      local_var_path = "/v1/tracking/stop"

      # query parameters
      query_params = {}
      query_params[:'carrier_code'] = opts[:'carrier_code'] if !opts[:'carrier_code'].nil?
      query_params[:'tracking_number'] = opts[:'tracking_number'] if !opts[:'tracking_number'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['api-key']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrackingApi#stop_tracking\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :carrier_code 
    # @option opts [String] :tracking_number 
    # @return [Array<(TrackingInformation, Fixnum, Hash)>] TrackingInformation data, response status code and response headers
    def track_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: TrackingApi.track ..."
      end
      # resource path
      local_var_path = "/v1/tracking"

      # query parameters
      query_params = {}
      query_params[:'carrier_code'] = opts[:'carrier_code'] if !opts[:'carrier_code'].nil?
      query_params[:'tracking_number'] = opts[:'tracking_number'] if !opts[:'tracking_number'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['api-key']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'TrackingInformation')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrackingApi#track\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
