=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require "uri"

module ShipEngine
  class WarehousesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # 
    # 
    # @param request 
    # @param [Hash] opts the optional parameters
    # @return [WarehouseDTO]
    def create(request, opts = {})
      data, _status_code, _headers = create_with_http_info(request, opts)
      return data
    end

    # 
    # 
    # @param request 
    # @param [Hash] opts the optional parameters
    # @return [Array<(WarehouseDTO, Fixnum, Hash)>] WarehouseDTO data, response status code and response headers
    def create_with_http_info(request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: WarehousesApi.create ..."
      end
      # verify the required parameter 'request' is set
      if @api_client.config.client_side_validation && request.nil?
        fail ArgumentError, "Missing the required parameter 'request' when calling WarehousesApi.create"
      end
      # resource path
      local_var_path = "/v1/warehouses"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json', 'text/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(request)
      auth_names = ['api-key']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'WarehouseDTO')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: WarehousesApi#create\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # 
    # @param warehouse_id 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def delete(warehouse_id, opts = {})
      delete_with_http_info(warehouse_id, opts)
      return nil
    end

    # 
    # 
    # @param warehouse_id 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def delete_with_http_info(warehouse_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: WarehousesApi.delete ..."
      end
      # verify the required parameter 'warehouse_id' is set
      if @api_client.config.client_side_validation && warehouse_id.nil?
        fail ArgumentError, "Missing the required parameter 'warehouse_id' when calling WarehousesApi.delete"
      end
      # resource path
      local_var_path = "/v1/warehouses/{warehouse_id}".sub('{' + 'warehouse_id' + '}', warehouse_id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['api-key']
      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: WarehousesApi#delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # 
    # @param warehouse_id 
    # @param [Hash] opts the optional parameters
    # @return [WarehouseDTO]
    def get(warehouse_id, opts = {})
      data, _status_code, _headers = get_with_http_info(warehouse_id, opts)
      return data
    end

    # 
    # 
    # @param warehouse_id 
    # @param [Hash] opts the optional parameters
    # @return [Array<(WarehouseDTO, Fixnum, Hash)>] WarehouseDTO data, response status code and response headers
    def get_with_http_info(warehouse_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: WarehousesApi.get ..."
      end
      # verify the required parameter 'warehouse_id' is set
      if @api_client.config.client_side_validation && warehouse_id.nil?
        fail ArgumentError, "Missing the required parameter 'warehouse_id' when calling WarehousesApi.get"
      end
      # resource path
      local_var_path = "/v1/warehouses/{warehouse_id}".sub('{' + 'warehouse_id' + '}', warehouse_id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['api-key']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'WarehouseDTO')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: WarehousesApi#get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @return [WarehouseListDTO]
    def list(opts = {})
      data, _status_code, _headers = list_with_http_info(opts)
      return data
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @return [Array<(WarehouseListDTO, Fixnum, Hash)>] WarehouseListDTO data, response status code and response headers
    def list_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: WarehousesApi.list ..."
      end
      # resource path
      local_var_path = "/v1/warehouses"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['api-key']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'WarehouseListDTO')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: WarehousesApi#list\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # 
    # @param warehouse_id 
    # @param request 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def update(warehouse_id, request, opts = {})
      update_with_http_info(warehouse_id, request, opts)
      return nil
    end

    # 
    # 
    # @param warehouse_id 
    # @param request 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def update_with_http_info(warehouse_id, request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: WarehousesApi.update ..."
      end
      # verify the required parameter 'warehouse_id' is set
      if @api_client.config.client_side_validation && warehouse_id.nil?
        fail ArgumentError, "Missing the required parameter 'warehouse_id' when calling WarehousesApi.update"
      end
      # verify the required parameter 'request' is set
      if @api_client.config.client_side_validation && request.nil?
        fail ArgumentError, "Missing the required parameter 'request' when calling WarehousesApi.update"
      end
      # resource path
      local_var_path = "/v1/warehouses/{warehouse_id}".sub('{' + 'warehouse_id' + '}', warehouse_id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json', 'text/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(request)
      auth_names = ['api-key']
      data, status_code, headers = @api_client.call_api(:PUT, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: WarehousesApi#update\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
