=begin
#ShipEngine

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1-SNAPSHOT

=end

require "uri"

module ShipEngineApi
  class TrackingApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # 
    # 
    # @param api_key API Key
    # @param [Hash] opts the optional parameters
    # @option opts [String] :carrier_code 
    # @option opts [String] :tracking_number 
    # @return [nil]
    def tracking_start_tracking(api_key, opts = {})
      tracking_start_tracking_with_http_info(api_key, opts)
      return nil
    end

    # 
    # 
    # @param api_key API Key
    # @param [Hash] opts the optional parameters
    # @option opts [String] :carrier_code 
    # @option opts [String] :tracking_number 
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def tracking_start_tracking_with_http_info(api_key, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: TrackingApi.tracking_start_tracking ..."
      end
      # verify the required parameter 'api_key' is set
      if @api_client.config.client_side_validation && api_key.nil?
        fail ArgumentError, "Missing the required parameter 'api_key' when calling TrackingApi.tracking_start_tracking"
      end
      # resource path
      local_var_path = "/v1/tracking/start"

      # query parameters
      query_params = {}
      query_params[:'carrier_code'] = opts[:'carrier_code'] if !opts[:'carrier_code'].nil?
      query_params[:'tracking_number'] = opts[:'tracking_number'] if !opts[:'tracking_number'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/json'])
      header_params[:'api-key'] = api_key

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['api-key']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrackingApi#tracking_start_tracking\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # 
    # @param api_key API Key
    # @param [Hash] opts the optional parameters
    # @option opts [String] :carrier_code 
    # @option opts [String] :tracking_number 
    # @return [nil]
    def tracking_stop_tracking(api_key, opts = {})
      tracking_stop_tracking_with_http_info(api_key, opts)
      return nil
    end

    # 
    # 
    # @param api_key API Key
    # @param [Hash] opts the optional parameters
    # @option opts [String] :carrier_code 
    # @option opts [String] :tracking_number 
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def tracking_stop_tracking_with_http_info(api_key, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: TrackingApi.tracking_stop_tracking ..."
      end
      # verify the required parameter 'api_key' is set
      if @api_client.config.client_side_validation && api_key.nil?
        fail ArgumentError, "Missing the required parameter 'api_key' when calling TrackingApi.tracking_stop_tracking"
      end
      # resource path
      local_var_path = "/v1/tracking/stop"

      # query parameters
      query_params = {}
      query_params[:'carrier_code'] = opts[:'carrier_code'] if !opts[:'carrier_code'].nil?
      query_params[:'tracking_number'] = opts[:'tracking_number'] if !opts[:'tracking_number'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/json'])
      header_params[:'api-key'] = api_key

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['api-key']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrackingApi#tracking_stop_tracking\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # 
    # @param api_key API Key
    # @param [Hash] opts the optional parameters
    # @option opts [String] :carrier_code 
    # @option opts [String] :tracking_number 
    # @return [TrackingInformation]
    def tracking_track(api_key, opts = {})
      data, _status_code, _headers = tracking_track_with_http_info(api_key, opts)
      return data
    end

    # 
    # 
    # @param api_key API Key
    # @param [Hash] opts the optional parameters
    # @option opts [String] :carrier_code 
    # @option opts [String] :tracking_number 
    # @return [Array<(TrackingInformation, Fixnum, Hash)>] TrackingInformation data, response status code and response headers
    def tracking_track_with_http_info(api_key, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: TrackingApi.tracking_track ..."
      end
      # verify the required parameter 'api_key' is set
      if @api_client.config.client_side_validation && api_key.nil?
        fail ArgumentError, "Missing the required parameter 'api_key' when calling TrackingApi.tracking_track"
      end
      # resource path
      local_var_path = "/v1/tracking"

      # query parameters
      query_params = {}
      query_params[:'carrier_code'] = opts[:'carrier_code'] if !opts[:'carrier_code'].nil?
      query_params[:'tracking_number'] = opts[:'tracking_number'] if !opts[:'tracking_number'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/json'])
      header_params[:'api-key'] = api_key

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['api-key']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'TrackingInformation')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrackingApi#tracking_track\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
